### ISSUE TITLE
already subscribed(105) Errors

### ISSUE THREAD

**Issue by onato** [centrifugal/centrifuge-swift#49] opened 2021-08-27 03:59 UTC
I have a `UIViewController` inside a `UINavigationController` which is inside a `UISplitViewController`. On a large phone when you tap the back button the view controller is not immediately deallocated in case you rotate the phone. In this case the view controller will be displayed in an expanded split view. 

<img width="887" alt="Screen Shot 2021-08-27 at 3 55 49 PM" src="https://user-images.githubusercontent.com/107999/131069481-75f8d89a-8eb1-4fdb-82e8-e478882f0b86.png">

What this means is that the `deinit` of the old screen is not called until just before the new screen is set up. I am removing subscriptions in `deinit` and creating them in `viewDidLoad`. These happen quite close to one another. It works most of the time but every so often I get an error that I am already subscribed to the channel. Looking at the code I think I can see where it is going wrong.

In the following method, the `unsubscribe` method returns immediately, but its contents run on `syncQueue`. If this is backed up the `subscriptionsLock` is released before the `Client.unsubscribe(sub:)` is performed. For this to be bulletproof it would need to use completion handlers and a DispatchGroup to wait until all unsubscribes are done. Although this could have performance implications.

https://github.com/centrifugal/centrifuge-swift/blob/dc4bde7a4c8316574829fb293f73bae6dab3d441/Sources/SwiftCentrifuge/Client.swift#L268-L278

On a side note, it shouldn't be possible to have more than one subscription with the same `channel`. This would suggest that the `removeSubscription` could be simplified. In this case, a simple completion handler would do the trick. 

I would be happy to put together a demo project if you would let me know of a public server I could connect to.

**Comment by onato** [comment] 2021-08-30 01:37
Your pull request did improve things slightly. When I am subscribing to just one channel I haven't been able to reproduce the issue, however, when I repeatedly push and pop a screen that subscribes to many channels I still can.

I added the following to enable me to remove multiple subscriptions whilst only locking an unlocking once. This had the effect of making the error much easier to reproduce.

```swift
    /**
     * Tell Client that Subscription should be removed from internal registry. Subscription will be
     * automatically unsubscribed before removing.
     - parameter sub: CentrifugeSubscription
     */
    public func removeSubscription(_ sub: CentrifugeSubscription) {
        removeSubscriptions([sub])
    }

    /**
     * Tell Client that Subscriptions should be removed from internal registry. Each subscription will be
     * automatically unsubscribed before removing.
     - parameter subscriptions: [CentrifugeSubscription]
     */
    public func removeSubscriptions(_ subscriptions: [CentrifugeSubscription]) {
        defer { subscriptionsLock.unlock() }
        subscriptionsLock.lock()
        for sub in subscriptions {
            self.subscriptions
                .filter({ $0.channel == sub.channel })
                .forEach { sub in
                    sub.unsubscribe()
                }
            self.subscriptions.removeAll(where: { $0.channel == sub.channel })
        }
    }
```

You can see in [my log file](https://gist.github.com/onato/8de492c57224e907ed23e9250a9ded81) that each channel is removed and created in the correct order but I still get multiple "already subscribed(105)" errors.

Presently, I'm thinking that the only way this could happen is if the messages over the web socket are in the wrong order or the server is complaining about the subscribe happening before it has finished unsubscribing. I tried to inspect the WebSocket traffic in Charles but couldn't yet decode the packets to verify the order. To be able to do this I added the following to [Client.swift](https://github.com/centrifugal/centrifuge-swift/blob/dc4bde7a4c8316574829fb293f73bae6dab3d441/Sources/SwiftCentrifuge/Client.swift#L196) allow Charlse to inspect the traffic.

```swift
    request.addValue("application/x-protobuf", forHTTPHeaderField: "Content-Type")

    let stream = FoundationStream()
    stream.enableSOCKSProxy = true

    let ws = WebSocket(request: request, stream: stream)

```

Charles wants to be able to know how to decode the message. I'm not sure where to find the "Descriptor Registry".

<img width="527" alt="Screen Shot 2021-08-30 at 1 33 56 PM" src="https://user-images.githubusercontent.com/107999/131273635-e62041b3-c4bc-456a-9c85-79c7d89fe3c6.png">

**Comment by FZambia** [comment] 2021-08-30 06:47
@onato could you also post server configuration and maybe extend the example in repo to reproduce this? Connecting to locally running Centrifugo. Having the full reproducing example will simplify debugging a lot.

I'll also try to reproduce this locally in the meanwhile. And will think more on possible reason from both client and server sides.

**Comment by FZambia** [comment] 2021-08-30 07:10
I think I see one more possible way of happening:
1. Unsubscribe is called, the call put to sync queue, but inside this call we are using syncQueue.async again when calling `centrifuge?.unsubscribe` (so that it can be executed after step 2, i.e. after call to subscribe)
2. Subscribe called - the call put on sync queue

**Comment by FZambia** [comment] 2021-08-30 07:26
Updated my pr with 134e92b4a7e81de7b1ecee8b84a2639d21ce69f0 - please take a look?

**Comment by onato** [comment] 2021-08-30 08:02
I updated and I am still able to reproduce the error. I'll try and update the example as you suggested.

**Comment by FZambia** [comment] 2021-08-30 09:10
I think I was able to reproduce this with these changes in example:

```diff
diff --git a/Example/SwiftCentrifuge/ViewController.swift b/Example/SwiftCentrifuge/ViewController.swift
index 05ca74f..6b05502 100644
--- a/Example/SwiftCentrifuge/ViewController.swift
+++ b/Example/SwiftCentrifuge/ViewController.swift
@@ -56,6 +56,20 @@ class ViewController: UIViewController {
         }
     }
     
+    private func resubscribe() {
+        DispatchQueue.main.asyncAfter(deadline: .now() + 0.2) {
+            self.client?.removeSubscription(self.sub!)
+            do {
+                self.sub = try self.client?.newSubscription(channel: "chat:index", delegate: self)
+            } catch {
+                print("Can not create subscription: \(error)")
+                return
+            }
+            self.sub?.subscribe()
+            self.resubscribe()
+        }
+    }
+    
     private func createSubscription() {
         do {
             sub = try self.client?.newSubscription(channel: "chat:index", delegate: self)
@@ -64,6 +78,8 @@ class ViewController: UIViewController {
             return
         }
         sub?.subscribe()
+        
+        resubscribe()
     }
 }

```

The interesting observation is that if I only use:

```
    private func resubscribe() {
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.2) {
            self.sub?.unsubscribe()
            self.sub?.subscribe()
            self.resubscribe()
        }
    }
``` 

I.e. without calling `removeSubscription` - then I don't see 105 errors.

**Comment by FZambia** [comment] 2021-08-30 09:30
Now I see that `unsubscribe` command not sent to the server at all in some cases.

**Comment by onato** [comment] 2021-08-30 09:34
Cool! Sounds like we're closing in on the root cause.

For what it's worth, this is my server config…

```
{
 "v3_use_offset": true,
 "token_hmac_secret_key": "xxxx",
 "admin_password": "xxxx",
 "admin_secret": "xxxx",
 "api_key": "xxx",
 "namespaces": [
  {
   "name": "tribe",
   "presence": true
  },
  {
   "name": "tribe-presence-e",
   "presence": true,
   "join_leave": true
  },
  {
   "name": "tribe-publishable",
   "presence": true,
   "publish": true,
   "subscribe_to_publish": true
  }
 ]
}
```

**Comment by FZambia** [comment] 2021-08-30 11:01
Pushed one more commit which I believe should fix errors. But the trade-off there is that Subscription unsubscribe callback won't be called since looks like Subscription is deallocated till the moment we can call it. And that was actually the root of the problem:

```swift
    public func unsubscribe() {
        self.centrifuge?.syncQueue.async { [weak self] in
            guard let strongSelf = self else { return }
            strongSelf.needResubscribe = false
            strongSelf.needRecover = false
            strongSelf.moveToUnsubscribed()
            strongSelf.centrifuge?.unsubscribe(sub: strongSelf)
        }
    }
```

Inside `unsubscribe` func guard `guard let strongSelf = self else { return }` resulted in a `return` so that no unsubscribe request has been sent for a Subscription object which was just removed from  the client registry.

Not sure at the moment whether a better way exists.

**Comment by onato** [comment] 2021-08-30 11:18
Yes! That did the trick. I can't reproduce the error anymore. I'll create a new build tomorrow and watch the logs.

You could capture `self` in this case since the async code will always run shortly afterward. After it finishes running the block will be deallocated and subsequently, `self` will also.

**Comment by FZambia** [comment] 2021-08-30 11:19
> You could capture self in this case since the async code will always run shortly afterward. After it finishes running, the block will be deallocated and subsequently, self will also.

Could you show on example when you have time? I am not a Swift developer form, so not really strong in Swift memory model

**Comment by onato** [comment] 2021-08-31 00:04
You can change `unsubscribe` to…

```swift
public func unsubscribe() {
     self.centrifuge?.syncQueue.async {
          self.needResubscribe = false
          self.needRecover = false
          self.moveToUnsubscribed()
          self.centrifuge?.unsubscribe(sub: self)
      }
}
```
You can do this in many of the places where you use `strongSelf`. If you want to make sure that you have not created a retain cycle you can add a log message to the `deinit` so you can verify that the object is being deallocated.

```swift
deinit {
    debugPrint("deinit")
}
```

By referencing `self` in the block you make sure that it stays around until the `syncQueue` releases it. This happens soon after it has been executed at which point the block no longer retains self and the subscription can then be deallocated.

**Comment by FZambia** [comment] 2021-08-31 07:44
Thanks!

Just updated pr so that unsubscribe callback called for removed Subscription. Also merged yesterday's changes from master branch into that pr, see [0.4.0](https://github.com/centrifugal/centrifuge-swift/releases/tag/0.4.0).

Waiting for a signal from you whether it's ok or maybe sth still needs to be improved.

**Comment by onato** [comment] 2021-09-01 06:03
I wasn't able to reproduce any `already subscribed` errors, so it's looking good.

**Closed as completed** 2021-09-02 08:07 UTC
